// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for android - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.iOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for ios - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyB5zm3wq71udoE9Kr04E8KFQGqw_D8MiiQ',
    appId: '1:151771140574:web:24b70a0e6e7c48e27a4d4f',
    messagingSenderId: '151771140574',
    projectId: 'theeraphat-43291',
    authDomain: 'theeraphat-43291.firebaseapp.com',
    storageBucket: 'theeraphat-43291.firebasestorage.app',
    measurementId: 'G-CQD8N02M2K',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyB5zm3wq71udoE9Kr04E8KFQGqw_D8MiiQ',
    appId: '1:151771140574:web:3c8317c15402d7027a4d4f',
    messagingSenderId: '151771140574',
    projectId: 'theeraphat-43291',
    authDomain: 'theeraphat-43291.firebaseapp.com',
    storageBucket: 'theeraphat-43291.firebasestorage.app',
    measurementId: 'G-VJ7GCYJ5MC',
  );
}
